stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/news.csv
    outs:
    -  data/raw/news.csv

  pre-processing:
    cmd: python src/pre_processing.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/pre_processing.py
    - data/raw/news.csv
    outs:
    - data/pre-processed/news.csv

  train-test-split:
    cmd: python src/train_test_split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/train_test_split_data.py
    - data/pre-processed/news.csv
    outs:
    - data/processed/train_news.csv
    - data/processed/test_news.csv
  
  model-training:
    cmd: python src/training_and_evaluation.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/training_and_evaluation.py
    - data/processed/train_news.csv
    - data/processed/test_news.csv
    params:
    - estimators.model-1.params.C
    metrics:
    - report/scores.json:
      cache: false
    - report/params.json:
      cache: false

    outs:
    - saved_models/model-1.joblib