base:
  project: FakeNewsClassification
  target_col: label

data_source:
  source: data_given/news.csv

load_data:
  raw_dataset_csv: data/raw/news.csv

pre_processing:
  pre-processed_csv: data/pre-processed/news.csv

split_data:
  train_path: data/processed/train_news.csv
  test_path: data/processed/test_news.csv
  test_size: 0.2
  random_state: 3

processing: prediction_service\processing_transformers

estimators:
  model-1:
    params:
      # C: 0.8
      # C: 0.6
      C: 1

model-dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

prediction:
  final-model: prediction_service/model/model-1.joblib
